### ISSUE TITLE
Gr8 Work - But needs a compact storage alternative

### ISSUE THREAD

**Issue by innatepassion** [janezkranjc/twitter-tap#1]
The data should be broken down,structured & saved in DB's like sqllite or something. Which would make the DB's compact & easy to run from was ec2.

Presently it consumes ec2 capacity within a day.

Gr8 work. very simple interface.

**Comment by janezkranjc** [comment]
hey man

i added another project https://github.com/janezkranjc/tweetset

it's a django web app that stores tweets to a database. you can read more about it in the readme
