### ISSUE TITLE
Twitter REST API missing geo-tagged tweets from Europe

### ISSUE THREAD

**Issue by dkocich** [janezkranjc/twitter-tap#4]
Hello,
did you noticed something like this in your app? I was using it few weeks, everything was ok and now I have this issue. Maybe it is not related to Twitter-tap. I am just trying to ask if it could be related to your software.

http://gis.stackexchange.com/questions/168622/twitter-rest-api-missing-geo-tagged-tweets-from-europe

Issue is also here:
https://twittercommunity.com/t/twitter-rest-api-missing-geo-tagged-tweets-from-europe/55635

Thanks for your time. Have a nice day.

**Comment by janezkranjc** [comment]
It's most probably not related. I'll check it out anyway!
